### ISSUE TITLE
Compatibility with USD Version 18.09

### ISSUE THREAD

**Issue by madoodia** [AnimalLogic/AL_USDMaya#107]
Hi guys
I wonder The Current Version of Al_USDMaya is compatible with USD Version 18.09 or we should wait for next release?

thanks

**Comment by fabal** [comment]
Hi @madoodia , to use AL_USDMaya with USD-0.18.9 (release 18.09) you will need to recompile it but from what I've seen this should be straightforward.
We'll update the plugin soon anyway.

**Comment by elrond79** [comment]
@fabal - Have you guys actually actually done the work for getting the code compatible with 18.09? I ask because:

a) due to a massive refactor of all of Pixar's maya code, there's a greater than normal amount of code change
b) we've actually already made all the necessary changes (mostly a lot of stuff was renamed), and we were just about to make a PR

**Comment by elrond79** [comment]
Actually... my mistake, I forgot that you guys don't generally link against pixar's usdMaya.  There aren't too many changes, and what is there mostly relates to a PR we made!

**Comment by fabal** [comment]
That's correct @elrond79 , for now at least, we don't rely on pixar's usdMaya.
The changes are already ready on our side, it's now a matter of releasing everything internally first. Shouldn't be too long until the official release.

**Comment by elrond79** [comment]
Hi - so when looking at this, we realized that our earlier PR actually caused some runtime linkage errors.  To fix this, we've made a revised PR that completely segregates / sandboxes the pixar translator for AL proxy shapes into it's own maya plugin. Find it here:

https://github.com/AnimalLogic/AL_USDMaya/pull/109

Apologies!
