### ISSUE TITLE
USD dev branch removes UsdImagingGLHdEngine, breaks compilation

### ISSUE THREAD

**Issue by murphyeoin** [AnimalLogic/AL_USDMaya#128]
[UsdImagingGL/hdEngine.h](https://github.com/PixarAnimationStudios/USD/blob/6c50b29bb76f0a7c176bae05668ab195520a019b/pxr/usdImaging/lib/usdImagingGL/hdEngine.h#L59) was made private as part of a refactor, see:
+ https://github.com/PixarAnimationStudios/USD/commit/e174a37b3613654eadc12dfebd7f2e108080b9ce
+ https://github.com/PixarAnimationStudios/USD/commit/cb884874f5effc7f71ac8ca8333903409c657cab
and a number of other commits by @c64kernal currently on the dev branch

Currently, AL_USDMaya creates an instance of UsdImagingGLHdEngine. We should update to using UsdImagingGL

@sirpalee thanks for the report

**Comment by c64kernal** [comment]
Thanks guys!  I'd recommend going straight to UsdImagingGLEngine -- skip UsdImagingGL, it's about to disappear too.  Let me know if you run into any trouble at all, and I'd be happy to help.

**Comment by murphyeoin** [comment]
Thanks George (sorry, I hadn't realised it was you!), we'll give it a try and let you know

**Comment by sirpalee** [comment]
@c64kernal I started updating AL_USDMaya at Luma to get some tests rolling with the latest USD dev branch. I found this commit: https://github.com/PixarAnimationStudios/USD/commit/5b226e0c57191e8fcbf198eba48e57a33c75d142 and AL_USDMaya rely on TestIntersectionBatch for selections in Maya. It doesn't look like that we have any alternatives.

**Comment by c64kernal** [comment]
Hi @sirpalee  -- really sorry about that!  It was unused code in our tree so we didn't think anyone else was using it either.  The question of how to move forward is interesting.   It seems like AL_USDMaya may be the only client of this code at all.  I worry that simply introducing it back into the tree would result in someone else coming along and removing it, like I did.

The other option of exposing enough of the innards to let you implement it yourself (basically making the trask controller accessible) might be okay, but I might be met with some (very understandable) resistance about breaking an abstraction.

Let me talk to some more folks tomorrow and see what we can do.  In the meantime, if there's anything that you can think about that we could do, please let us know!  At this point, I'm going to consider this a release-blocking issue, until I hear from you that you're okay to go.

Thanks Pal, and apologies again for the trouble.

**Comment by c64kernal** [comment]
That's a good idea, @sirpalee -- and wow, all that stuff is still protected, totally by accident :)  I should at least add a comment saying that folks are depending on it being protected now, so that we don't "fix" it and make it all private.

That sounds like a good way to go for now.  I'll talk to more folks tomorrow and I'll let you know if anyone else has any better ideas -- and I feel much better that you're unstuck with this proposal.

**Comment by c64kernal** [comment]
Hi again, @sirpalee -- I talked to the team about this, and it seems like subclassing is the way to go for this release, so that you get unstuck.  However, it's not ideal because of the reasons I mentioned above -- so our proposal, is to merge the two APIs into TestIntersection.  We'd take a PR for that, if you have time to make one, and then when that gets rolled out you can remove the subclass... does that sound okay with you?

**Comment by sirpalee** [comment]
@c64kernal sounds good! Let us get this change in al_usdmaya first, and I'll look into adding back functionality upstream for the next release.

**Comment by c64kernal** [comment]
Thanks very @sirpalee -- really appreciate it.
