### ISSUE TITLE
Public usd-docker?

### ISSUE THREAD

**Issue by mrharris** [AnimalLogic/AL_USDMaya#14]
Hi

I'm hitting issues in the 3 ways I tried to build (I'm a cmake/docker beginner so maybe other beginners will stumble across this too)

1. Docker  
Do you intend to release the docker-usd repo https://github.com/AnimalLogic/docker-usd? At the moment I am attempting with mottosso/maya/ from dockerhub by changing the FROM in Dockerfile_centos7#L4 but not getting far (`cmake: command not found`)

2. build_alusdmaya.sh  
Errors early whether in docker or standalone because TMP_DIR is not defined so raises `mkdir: missing operand`

3. build_lib.sh
I'm just learning cmake, so probably my build string is silly. I needed to add in `-DUSD_CONFIG_FILE='/usr/local/USD/pxrConfig.cmake` to build_lib.sh, but still haven't been able to get past the errors

```
cmake -Wno-dev \
      -DCMAKE_INSTALL_PREFIX='/usr/local/AL_USDMaya' \
      -DCMAKE_MODULE_PATH='/usr/local/USD/cmake;/home/lharris/git/AL_USDMaya/cmake/modules;/home/lharris/git/USD/cmake/modules' \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DBOOST_ROOT='/usr/local/USD/build/boost' \
      -DMAYA_LOCATION='/usr/autodesk/maya' \
      -DOPENEXR_LOCATION='/usr/local/USD/build/OpenEXR'\
      -DOPENGL_gl_LIBRARY='/usr/lib64/libglfw.so'\
      -DGLEW_LOCATION='/usr/local/USD/lib64/libGLEW.a'\
      -DUSD_CONFIG_FILE='/usr/local/USD/pxrConfig.cmake'\
      ..


-- Found the following Boost libraries:
--   python
CMake Error at CMakeLists.txt:87 (add_subdirectory):
  add_subdirectory given source "lib" which is not an existing directory.


CMake Error at CMakeLists.txt:88 (add_subdirectory):
  add_subdirectory given source "plugin" which is not an existing directory.


-- Building AL_USDMayaSchemas
CMake Error at CMakeLists.txt:96 (add_subdirectory):
  add_subdirectory given source "schemas" which is not an existing directory.
```

**Comment by dbaz** [comment]
Hi Paul,
We have discussed removing these docker files until will we opensource the base dockerfiles, since their existence might hinder people more than help. Let me know what you think.

1.
We are looking into releasing our source for the docker images. I have no ETA yet but I expect sooner than later.

2.
TMP_DIR is defined in our more base image, so you will have to set it yourself in your Docker file through and ENV or just directly in shell script.
In our more base image we set it in a Docker ENV command, somewhat like the following:
```
# In Dockerfile
ENV  BUILD_DIR=/opt/usd \
    TMP_DIR=/tmp/usd-build \
    DOWNLOADS_DIR=/tmp/usd-downloads
```

3.
That cmake command assumes it is being run inside a folder in the AL_USDMaya root folder, that is what the sneaky '..' at the end is saying. Like in the build_alusdmaya.sh, create a build folder in your AL_USDMaya, cd into it and run the cmake command and see if that fixes that issue.

```
    cd AL_USDMaya
    mkdir build
    cd build  
      cmake -Wno-dev \
            -DCMAKE_INSTALL_PREFIX=$BUILD_DIR \
            -DCMAKE_MODULE_PATH=$BUILD_DIR \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DBOOST_ROOT=$BUILD_DIR \
            -DMAYA_LOCATION=$MAYA_LOCATION \
            -DGTEST_ROOT=$BUILD_DIR \
            -DUSD_CONFIG_FILE=$BUILD_DIR/pxrConfig.cmake \
            -DCMAKE_PREFIX_PATH=$MAYA_LOCATION/lib/cmake \
            ..
```
Hopefully that helps a bit more, let me know if you need more info.

Baz

**Comment by mrharris** [comment]
Perfect thanks Baz. Got it built :)
It wasn't clear that $BUILD_DIR was the USD installation dir (/usr/local/USD in my case) and that alone could be used to satisfy so many of the cmake requirements
Now I will need to move off my centos virtual machine; legacy viewport doesn't seem to like hydra...
